blah <- read.table("blah.dat", col.names = c("bins", "fft_speed", "dft_speed", "fft_error", "dft_error", "kahan_error"))
fft_speed_model <- deriv(~ a / x / log(x), "a", function(a, x){})
dft_speed_model <- deriv(~ a / x / x, "a", function(a, x){})
fft_error_model <- deriv(~ a * log(x), c("a"), function(a, x){})
dft_error_model <- deriv(~ a * sqrt(x), c("a"), function(a, x){})
fft_speed_fit <- nls(fft_speed ~ fft_speed_model(a, bins), data = blah, start = list(a = 1))
dft_speed_fit <- nls(dft_speed ~ dft_speed_model(a, bins), data = blah, start = list(a = 1))
fft_error_fit <- nls(fft_error ~ fft_error_model(a, bins), data = blah, start = list(a = 1))
dft_error_fit <- nls(dft_error ~ dft_error_model(a, bins), data = blah, start = list(a = 1e-16))
a = coef(fft_speed_fit)
b = coef(dft_speed_fit)
c = coef(fft_error_fit)
d = coef(dft_error_fit)
par(mfrow = c(2, 2))
plot(fft_speed ~ bins, data = blah, log = "xy", main = bquote(.(a)~"/(n*log(n))"), xlab = "bin count (log scale)", ylab = "fft/s (log scale)")
curve(fft_speed_model(a, x), add = TRUE)
plot(dft_speed ~ bins, data = blah, log = "xy", main = bquote(.(b)~"/(n*n)"), xlab = "bin count (log scale)", ylab = "dft/s (log scale)")
curve(dft_speed_model(b, x), add = TRUE)
plot(fft_error ~ bins, data = blah, log = "x", main = bquote(.(c)~"*log(n)"), xlab = "bin count (log scale)", ylab = "fft error (lin scale)")
curve(fft_error_model(c, x), add = TRUE)
plot(dft_error ~ bins, data = blah, log = "xy", main = bquote(.(d)~"*sqrt(n)"), xlab = "bin count (log scale)", ylab = "dft error (log scale)")
curve(dft_error_model(d, x), add = TRUE)
